version: 1.0.{build}

branches:
  only:
    - release

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

before_build:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - appveyor DownloadFile https://raw.githubusercontent.com/appveyor/ci/master/scripts/nuget-restore.cmd
  - nuget-restore

build:
  project: RandomNet.sln

test:
  assemblies:
    - '**\*.Tests.dll'

after_test:
  - ps: .\nuget\pack.ps1

artifacts:
  - path: RandomNet\bin\Release\RandomNet.dll
    name: RandomNet.dll
  - path: '**\*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: 4MBiCVgduJ+5E6lzASSOmhHUb+XlTEfU56vsO1iC3pp/bJkkdcgii9RARoTzOKax
  artifact: /RandomNet.*\.nupkg/
