version: 1.0.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

build:
  project: RandomNet.sln

test:
  assemblies:
    - '**\*.tests.dll'

after_test:
  - ps: .\nuget\pack.ps1

artifacts:
  - path: RandomNet\bin\Release\RandomNet.dll
    name: RandomNet.dll
  - path: '**\*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: 4MBiCVgduJ+5E6lzASSOmhHUb+XlTEfU56vsO1iC3pp/bJkkdcgii9RARoTzOKax
  artifact: /.*\.nupkg/
